### ISSUE TITLE
Heya

### ISSUE THREAD

**Issue by tunnckoCore** [aravindnc/ip-domain-filter#1]
Is there any reason to not using `ip-filter` directly in the `lib/ip-match.js`?

Anyway, just to note, I'm going to update it soon.

**Comment by aravindnc** [comment]
I'm expecting bool as return and also to generalize bool output in all cases.

**Comment by tunnckoCore** [comment]
You can still do `result === null`? Anyway, no problem, was just curious :)

**Comment by aravindnc** [comment]
@tunnckoCore Cool. Thanks for checking this out.
